update_fan:
  name: Update Fan
  description: Set fan power and speed.
  fields:
    fanonoff:
      required: true
      selector:
        number:
          min: 0
          max: 1
          step: 1
          mode: slider
      description: '0 = off, 1 = on'
    fanspeed:
      required: true
      selector:
        number:
          min: 0
          max: 4
          step: 1
          mode: slider
      description: Fan speed (0 to 4)

update_light:
  name: Update Light
  description: Set light power and brightness.
  fields:
    lightonoff:
      required: true
      selector:
        number:
          min: 0
          max: 1
          step: 1
          mode: slider
      description: '0 = off, 1 = on'
    brightness:
      required: true
      selector:
        number:
          min: 0
          max: 100
          step: 1
          mode: slider
      description: Brightness (0–100)

update_decolight:
  name: Update Decolight
  description: Set decolight power and brightness.
  fields:
    decolightonoff:
      required: true
      selector:
        number:
          min: 0
          max: 1
          step: 1
          mode: slider
      description: '0 = off, 1 = on'
    decolightbrightness:
      required: true
      selector:
        number:
          min: 0
          max: 100
          step: 1
          mode: slider
      description: Brightness (0–100)
