blueprint:
  name: Thermex – Fan and Light Control
  description: Control Thermex fan speed and light via user-defined trigger
  domain: automation
  input:
    trigger_event:
      name: Trigger
      description: Select what triggers this automation
      default: []
      selector:
        trigger:
    fan_speed:
      name: Fan Speed
      description: Set fan speed (0–4)
      default: 1
      selector:
        number:
          min: 0
          max: 4
          step: 1
    fan_on:
      name: Fan On
      description: Turn fan on (true/false)
      default: true
      selector:
        boolean:
    light_on:
      name: Light On
      description: Turn light on (true/false)
      default: true
      selector:
        boolean:
    light_brightness:
      name: Light Brightness
      description: Brightness level (0–100)
      default: 100
      selector:
        number:
          min: 0
          max: 100
          step: 1

trigger: !input trigger_event

action:
  - service: thermex_api.update_fan
    data:
      fanonoff: "{{ 1 if fan_on else 0 }}"
      fanspeed: !input fan_speed
  - service: thermex_api.update_light
    data:
      lightonoff: "{{ 1 if light_on else 0 }}"
      brightness: !input light_brightness
mode: single
